version: "3.9"

services:
  postgresql:
    image: "postgres:12"
    container_name: "s3-postgresql"
    hostname: ${POSTGRES_HOST}
    restart: "always"
    environment:
      PGUSER: ${POSTGRES_USER}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - "${PWD}/volumes/postgresql/pgdata:/var/lib/postgresql/data:rw"
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 2s
      timeout: 5s
      retries: 5
