"""empty message

Revision ID: 1031a349622d
Revises: 
Create Date: 2023-07-06 16:02:49.576421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1031a349622d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('item_type', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['item.item_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index('uix_folder_name_parent_id_1', 'item', ['name', sa.text("coalesce(parent_id, '00000000-0000-0000-0000-000000000000')")], unique=True)
    op.create_index('uix_item_id_name', 'item', ['item_id', 'name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix_item_id_name', table_name='item')
    op.drop_index('uix_folder_name_parent_id_1', table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###
